// Writes packages/butter-core/src/replay/font.ts: Archivo's Latin subset, in the weights the
// replay panel uses, as base64, so replays render the same on every machine without reading
// files at runtime. Re-run after updating @fontsource/archivo: node scripts/embed-font.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const repo = join(import.meta.dirname, '..');
const files = join(repo, 'node_modules/@fontsource/archivo/files');
const weights = [400, 500, 600];
const version = JSON.parse(
  readFileSync(join(repo, 'node_modules/@fontsource/archivo/package.json'), 'utf8'),
).version;
const entries = weights.map((w) => {
  const b64 = readFileSync(join(files, `archivo-latin-${w}-normal.woff2`)).toString('base64');
  return `  { weight: ${w}, woff2: '${b64}' },`;
});
writeFileSync(
  join(repo, 'packages/butter-core/src/replay/font.ts'),
  `// Generated by scripts/embed-font.mjs from @fontsource/archivo ${version}. Don't edit by hand.
// Archivo, Copyright 2020 The Archivo Project Authors, under the SIL Open Font License 1.1
// (ARCHIVO-OFL.txt in this package).
/* prettier-ignore */
export const ARCHIVO: { weight: number; woff2: string }[] = [
${entries.join('\n')}
];
`,
);
writeFileSync(
  join(repo, 'packages/butter-core/ARCHIVO-OFL.txt'),
  readFileSync(join(repo, 'node_modules/@fontsource/archivo/LICENSE')),
);
console.log('wrote font.ts and ARCHIVO-OFL.txt');
